project: 
  type: website
  
website:
  title: "CCR group at AUH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: doc/lab-meetings.qmd
        text: Lab meetings
      - href: doc/on-boarding.qmd
        text: On-boarding
  page-footer:
    center:
      - text: "License: CC BY 4.0"
        href: LICENSE.html

format:
  html:
    theme: simplex

knitr:
  opts_chunk:
    echo: false

execute:
  freeze: false
  echo: true

editor:
  markdown: 
    wrap: 72
    canonical: true
  
