---
title: "Lab meetings"
format: html
date: last-modified
---

```{r setup}
#| message: false
targets::tar_config_set(store = here::here("_targets"))
# library(tidyverse)
# library(targets)
```

```{r}
#| include: false
#| eval: false
# dplyr::bind_rows(
#   read_csv("data/labmeetings.csv") |> (\(.x){.x[-match("X",colnames(.x))]})(),
#   next_meetings(
#     day = "Monday",
#     index = 1,
#     start = as.Date("2025-01-01"),
#     stop = as.Date(as.Date("2025-01-01")+lubridate::dmonths(6))
#   )
# ) |>
#   write.csv(here::here("data/labmeetings.csv"),row.names = FALSE)

system(paste("open", here::here("data/labmeetings.csv")))
```

## Get the calendar on your device before your colleague! And then, please help your colleague.

Create a new subscription calendar in your calender and use this link
(or click and subscribe):
<webcal://raw.githubusercontent.com/agdamsbo/ccRauh/main/ccrauh_labmeeting.ics>

## Here are the upcoming lab-meetings

```{r}
targets::tar_read(gt_labmeeting) |>
  dplyr::mutate(dplyr::across(dplyr::everything(), \(.x){
    .x[is.na(.x)] <- "Uafklaret"
    .x
  })) |> 
dplyr::filter(Subject != "AFLYST") |>
  gt::gt()
```

## Standard meeting agenda

-   [ ] 10 min: Significant news from the group or outside

-   [ ] 20 min: Round of "What's going on"

-   [ ] 30 min: Topic talk and discussion
